# PotholeRisk: Data Exploration

## Objective

This notebook performs an initial exploration of the datasets used in the
PotholeRisk project.

Datasets:
- Karnataka Accident Dataset
- Bengaluru Traffic Dataset

Tasks:
- Load datasets
- Explore dataset dimensions
- Understand column information
- Identify missing values
- Perform descriptive statistics

No preprocessing or machine learning is performed here.

In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

pd.set_option("display.max_columns", None)
pd.set_option("display.width", 1000)

In [5]:
# Load Accident Dataset
accident_df = pd.read_csv("../dataset/accident/Copy of AccidentReports.csv")

# Load Traffic Dataset
traffic_df = pd.read_csv("../dataset/traffic/Banglore_traffic_Dataset.csv")

print("Datasets loaded successfully!")

print("\nAccident Dataset Shape:", accident_df.shape)
print("Traffic Dataset Shape:", traffic_df.shape)

UnicodeDecodeError: 'utf-8' codec can't decode byte 0x94 in position 109163: invalid start byte

In [ ]:
# Load Accident Dataset
accident_df = pd.read_csv(
    "../dataset/accident/Copy of AccidentReports.csv",
    encoding="latin1"
)

print("Accident dataset loaded successfully!")
print(accident_df.shape)

Accident dataset loaded successfully!
(301761, 36)

In [ ]:
traffic_df = pd.read_csv(
    "../dataset/traffic/Banglore_traffic_Dataset.csv"
)

print("Traffic dataset loaded successfully!")
print(traffic_df.shape)

Traffic dataset loaded successfully!
(8936, 16)

In [ ]:
# Display the first five rows of each dataset

print("========== Accident Dataset ==========")
display(accident_df.head())

print("\n========== Traffic Dataset ==========")
display(traffic_df.head())

========== Accident Dataset ==========

  DISTRICTNAME    UNITNAME      Crime_No  Year  RI  Noofvehicle_involved Accident_Classification Accident_Spot    Accident_Location       Accident_SubLocation Accident_SpotB   Main_Cause Hit_Run         Severity    Collision_Type Junction_Control  Road_Character      Road_Type  Surface_Type Surface_Condition  Road_Condition     Weather Lane_Type      Road_Markings Spot_Conditions       Side_Walk  RoadJunction Collision_TypeB                                      Accident_Road Landmark_first landmark_second Distance_LandMark_First Distance_LandMark_Second                               Accident_Description  Latitude  Longitude
0     Bagalkot  Amengad PS  1.047010e+16  2016   1                     1          Road Accidents    Bottleneck          Rural Areas                  Open area            NaN  Human Error      No  Grievous Injury           Drowned   Not Applicable           Curve  State Highway  Bitumen(Tar)               Dry  Not Applicable       Clear       NaN                NaN             NaN       Asphalted           NaN             NaN  AMINAGAD BAGALKOT SGH-20 ROAD NEAR TIPPANNA GO...              8             NaN                       8                      NaN  AMINAGADA TO BAGALKOT SH-20 ROAD NEAR TIPPANNA...       0.0        0.0
1     Bagalkot  Amengad PS  1.047010e+16  2016   1                     1          Road Accidents        Bridge  Villages settlement  Narrow bridge or culverts            NaN  Human Error      No            Fatal  Hit fixed object   Not Applicable          Others  State Highway  Bitumen(Tar)    Not Applicable  Not Applicable  Light Rain  DualLane  Centre White Line             NaN       Asphalted           NaN             NaN           SHIRUR AMINAGAD SH-20 ROAD NEAR KAMATAGI             14             NaN                      14                      NaN           SHIRUR AMINAGAD SH-20 ROAD NEAR KAMATAGI       0.0        0.0
2     Bagalkot  Amengad PS  1.047010e+16  2016   1                     2          Road Accidents    Bottleneck            City/Town     Near School or College            NaN  Human Error     Yes      Damage Only       Hit and Run   Not Applicable  Not Applicable  State Highway  Bitumen(Tar)               Dry  Not Applicable       Clear  DualLane  Centre White Line          Others       Asphalted           NaN             NaN  AMINAGAD TO BAGALKOT SH-20 ROAD NEAR BANATHIKOLLA   BANATHIKOLLA             NaN                       3                      NaN           AMINAGAD BAGALKOT SH-20 NEAR BANATHIKOLL       0.0        0.0
3     Bagalkot  Amengad PS  1.047010e+16  2016   1                     2          Road Accidents    Bottleneck          Rural Areas           Residential area            NaN  Human Error      No      Damage Only           Head on   Not Applicable  Not Applicable  State Highway  Bitumen(Tar)               Dry  Not Applicable       Clear  DualLane  Centre White Line          Others             NaN           NaN             NaN         AMINAGAD BAGALKOT ROAD NEAR ADILASHA HOTEL      500 MITER             NaN                    500M                      NaN  AMINAGAD BAGALKOT  SH-20 ROAD NEAR ADILSHA HOTELA       0.0        0.0
4     Bagalkot  Amengad PS  1.047010e+16  2016   1                     1          Road Accidents   Cross roads            City/Town     At pedestrian Crossing            NaN  Human Error     Yes            Fatal           Head on    Give way sign  Not Applicable  State Highway  Bitumen(Tar)               Dry  Not Applicable       Clear       NaN                NaN             NaN  Not Applicable           NaN             NaN  AMD TO BGK SH-20 ROAD NEAR AMINGAD SULEBAVI CROSS          100MM             NaN                   100MM                      NaN  AMD TO BGK SH-20 ROAD NEAR AMINAGAD SULEBAVI C...       0.0        0.0

========== Traffic Dataset ==========

         Date    Area Name Road/Intersection Name  Traffic Volume  Average Speed  Travel Time Index  Congestion Level  Road Capacity Utilization  Incident Reports  Environmental Impact  Public Transport Usage  Traffic Signal Compliance  Parking Usage  Pedestrian and Cyclist Count Weather Conditions Roadwork and Construction Activity
0  2022-01-01  Indiranagar          100 Feet Road           50590      50.230299           1.500000        100.000000                 100.000000                 0               151.180               70.632330                  84.044600      85.403629                           111              Clear                                 No
1  2022-01-01  Indiranagar               CMH Road           30825      29.377125           1.500000        100.000000                 100.000000                 1               111.650               41.924899                  91.407038      59.983689                           100              Clear                                 No
2  2022-01-01   Whitefield    Marathahalli Bridge            7399      54.474398           1.039069         28.347994                  36.396525                 0                64.798               44.662384                  61.375541      95.466020                           189              Clear                                 No
3  2022-01-01  Koramangala    Sony World Junction           60874      43.817610           1.500000        100.000000                 100.000000                 1               171.748               32.773123                  75.547092      63.567452                           111              Clear                                 No
4  2022-01-01  Koramangala          Sarjapur Road           57292      41.116763           1.500000        100.000000                 100.000000                 3               164.584               35.092601                  64.634762      93.155171                           104              Clear                                 No

In [ ]:
# Basic information about the datasets

print("========== Accident Dataset ==========")
print("Shape:", accident_df.shape)

print("\nColumns:")
print(accident_df.columns.tolist())

print("\n")

print("========== Traffic Dataset ==========")
print("Shape:", traffic_df.shape)

print("\nColumns:")
print(traffic_df.columns.tolist())

========== Accident Dataset ==========
Shape: (301761, 36)

Columns:
['DISTRICTNAME', 'UNITNAME', 'Crime_No', 'Year', 'RI', 'Noofvehicle_involved', 'Accident_Classification', 'Accident_Spot', 'Accident_Location', 'Accident_SubLocation', 'Accident_SpotB', 'Main_Cause', 'Hit_Run', 'Severity', 'Collision_Type', 'Junction_Control', 'Road_Character', 'Road_Type', 'Surface_Type', 'Surface_Condition', 'Road_Condition', 'Weather', 'Lane_Type', 'Road_Markings', 'Spot_Conditions', 'Side_Walk', 'RoadJunction', 'Collision_TypeB', 'Accident_Road', 'Landmark_first', 'landmark_second', 'Distance_LandMark_First', 'Distance_LandMark_Second', 'Accident_Description', 'Latitude', 'Longitude']


========== Traffic Dataset ==========
Shape: (8936, 16)

Columns:
['Date', 'Area Name', 'Road/Intersection Name', 'Traffic Volume', 'Average Speed', 'Travel Time Index', 'Congestion Level', 'Road Capacity Utilization', 'Incident Reports', 'Environmental Impact', 'Public Transport Usage', 'Traffic Signal Compliance', 'Parking Usage', 'Pedestrian and Cyclist Count', 'Weather Conditions', 'Roadwork and Construction Activity']

In [ ]:
accident_df["DISTRICTNAME"].value_counts()

DISTRICTNAME
Bengaluru City           34526
Tumakuru                 16738
Bengaluru Dist           15436
Hassan                   15365
Mandya                   15295
Belagavi Dist            15058
Chitradurga              11899
Shivamogga               11583
Mysuru Dist              10930
Ramanagara               10711
Udupi                     9327
Uttara Kannada            8607
Bidar                     8400
Mangaluru City            7828
Davanagere                7522
Vijayapur                 7327
Chikkamagaluru            7011
Dakshina Kannada          6782
Bagalkot                  6334
Mysuru City               6162
Haveri                    5615
Kalaburagi                5445
Chickballapura            5059
Raichur                   4830
Kolar                     4803
Belagavi City             4605
Koppal                    4476
Chamarajanagar            4438
Ballari                   4250
Vijayanagara              4240
Kodagu                    3781
Dharwad                   3531
Kalaburagi City           3527
Hubballi Dharwad City     3505
Yadgir                    2968
Gadag                     2673
K.G.F                     1135
Karnataka Railways          39
Name: count, dtype: int64

In [ ]:
# Filter only Bengaluru accidents

bengaluru_accidents = accident_df[
    accident_df["DISTRICTNAME"].isin(["Bengaluru City", "Bengaluru Dist"])
]

print("Total Bengaluru Accident Records:")
print(bengaluru_accidents.shape)

display(bengaluru_accidents.head())

Total Bengaluru Accident Records:
(49962, 36)

         DISTRICTNAME            UNITNAME      Crime_No  Year  RI  Noofvehicle_involved Accident_Classification Accident_Spot Accident_Location    Accident_SubLocation Accident_SpotB   Main_Cause         Hit_Run         Severity  Collision_Type  Junction_Control  Road_Character          Road_Type  Surface_Type Surface_Condition  Road_Condition Weather Lane_Type       Road_Markings Spot_Conditions Side_Walk  RoadJunction Collision_TypeB                    Accident_Road                      Landmark_first         landmark_second Distance_LandMark_First Distance_LandMark_Second                               Accident_Description  Latitude  Longitude
30247  Bengaluru City  Adugodi Traffic PS  1.044320e+16  2016   1                     1          Road Accidents   Cross roads         City/Town  At pedestrian Crossing            NaN  Human Error              No  Grievous Injury  Hit pedestrian  No signal lights  Not Applicable  City or Town Road  Bitumen(Tar)            Others  Not Applicable   Clear       NaN                 NaN             NaN       NaN           NaN             NaN                HOSUR LASKAR ROAD              GANESHA DARSHINI HOTEL  SANKALAPA NURSING HOME                   10MET                   20 MET  ?????? 10/01/2016 ???? ???????? ??? ??????? ??...       0.0        0.0
30248  Bengaluru City  Adugodi Traffic PS  1.044320e+16  2016   1                     3          Road Accidents    T Junction         City/Town           Near Bus stop            NaN  Human Error             Yes  Grievous Injury  Not Applicable        Controlled         Incline  City or Town Road  Bitumen(Tar)               Dry  Not Applicable    Fine       NaN                 NaN             NaN       NaN           NaN             NaN              Sarjapura main road                  Aishwarya junction                     NaN                     4km                      NaN  ??????;09/08/2016 ???? ???????? 09:40 ???? ???...       0.0        0.0
30249  Bengaluru City  Adugodi Traffic PS  1.044320e+16  2016   1                     1          Road Accidents         Other         City/Town               Open area            NaN  Human Error              No  Grievous Injury  Hit pedestrian      Uncontrolled         Incline  City or Town Road  Bitumen(Tar)               Dry  Not Applicable    Fine       NaN                 NaN             NaN       NaN           NaN             NaN                HOSUR LASKAR ROAD  NEAR CAR SOUTH POLICE QTRS ADUGODI                     NaN                  500MTR                      NaN  ??????;22/08/2016 ???? ??????? 01:00 ???? ????...       0.0        0.0
30250  Bengaluru City  Adugodi Traffic PS  1.044320e+16  2016   1                     1          Road Accidents         Other         City/Town           Near Bus stop            NaN  Human Error  Not Applicable  Grievous Injury          Others        Controlled         Incline  City or Town Road  Bitumen(Tar)               Dry  Not Applicable    Fine       NaN                 NaN             NaN       NaN           NaN             NaN  100  FEET RING ROAD KORAMANGALA        NEAR BDA COMPLEX KORAMANGALA                     NaN                     2KM                      NaN  ??????;04/09/2016 ???? ???????? 09:00 ???? ???...       0.0        0.0
30251  Bengaluru City  Adugodi Traffic PS  1.044320e+16  2016   1                     2          Road Accidents         Other         City/Town               Open area            NaN  Human Error              No      Damage Only        Rear end         Stop sign         Incline  City or Town Road  Bitumen(Tar)               Dry  Not Applicable    Fine       NaN  Centre Broken Line          Others  Concrete           NaN             NaN                      80feet road                                   1                       1                       1                        1  In this accident was happened in 80feet road k...       0.0        0.0

In [ ]:
print(bengaluru_accidents.shape)

(49962, 36)

In [ ]:
# Show all columns in the Bengaluru accident dataset

print("Total Columns:", len(bengaluru_accidents.columns))
print()

for i, col in enumerate(bengaluru_accidents.columns, start=1):
    print(f"{i}. {col}")

NameError: name 'bengaluru_accidents' is not defined

In [6]:
%whos

Variable   Type      Data/Info
------------------------------
np         module    <module 'numpy' from 'c:\<...>ges\\numpy\\__init__.py'>
pd         module    <module 'pandas' from 'c:<...>es\\pandas\\__init__.py'>
plt        module    <module 'matplotlib.pyplo<...>\\matplotlib\\pyplot.py'>

In [7]:
print("accident_df exists:", "accident_df" in globals())
print("traffic_df exists:", "traffic_df" in globals())
print("bengaluru_accidents exists:", "bengaluru_accidents" in globals())

accident_df exists: False
traffic_df exists: False
bengaluru_accidents exists: False

In [8]:
accident_df = pd.read_csv(
    "../dataset/accident/Copy of AccidentReports.csv",
    encoding="latin1"
)

print(accident_df.shape)

(301761, 36)

In [12]:
%whos

Variable              Type         Data/Info
--------------------------------------------
accident_df           DataFrame           DISTRICTNAME      <...>301761 rows x 36 columns]
bengaluru_accidents   DataFrame             DISTRICTNAME    <...>[49962 rows x 36 columns]
np                    module       <module 'numpy' from 'c:\<...>ges\\numpy\\__init__.py'>
pd                    module       <module 'pandas' from 'c:<...>es\\pandas\\__init__.py'>
plt                   module       <module 'matplotlib.pyplo<...>\\matplotlib\\pyplot.py'>
traffic_df            DataFrame                Date        A<...>n[8936 rows x 16 columns]

In [10]:
traffic_df = pd.read_csv(
    "../dataset/traffic/Banglore_traffic_Dataset.csv"
)

print(traffic_df.shape)

(8936, 16)

In [11]:
bengaluru_accidents = accident_df[
    accident_df["DISTRICTNAME"].isin(
        ["Bengaluru City", "Bengaluru Dist"]
    )
]

print(bengaluru_accidents.shape)

(49962, 36)

In [13]:

print("Total Columns:", len(bengaluru_accidents.columns))
print()

for i, col in enumerate(bengaluru_accidents.columns, start=1):
    print(f"{i}. {col}")

Total Columns: 36

1. DISTRICTNAME
2. UNITNAME
3. Crime_No
4. Year
5. RI
6. Noofvehicle_involved
7. Accident_Classification
8. Accident_Spot
9. Accident_Location
10. Accident_SubLocation
11. Accident_SpotB
12. Main_Cause
13. Hit_Run
14. Severity
15. Collision_Type
16. Junction_Control
17. Road_Character
18. Road_Type
19. Surface_Type
20. Surface_Condition
21. Road_Condition
22. Weather
23. Lane_Type
24. Road_Markings
25. Spot_Conditions
26. Side_Walk
27. RoadJunction
28. Collision_TypeB
29. Accident_Road
30. Landmark_first
31. landmark_second
32. Distance_LandMark_First
33. Distance_LandMark_Second
34. Accident_Description
35. Latitude
36. Longitude

In [14]:
# Explore categorical columns

categorical_columns = [
    "Weather",
    "Road_Condition",
    "Surface_Condition",
    "Road_Type",
    "Road_Character",
    "Collision_Type",
    "Main_Cause",
    "Severity"
]

for col in categorical_columns:
    print("\n" + "="*60)
    print(col)
    print("="*60)
    print(bengaluru_accidents[col].value_counts())

============================================================
Weather
============================================================
Weather
Clear                            22485
Fine                             19919
Others                            4190
Cloudy                            1219
Not Applicable                    1152
Fog / Mist                         306
Light Rain                         127
Very Cold                          111
Snow                                94
Very Hot                            85
Mist or Fog                         73
Wind                                70
Dust Storn                          46
Heavy Rain                          27
Hail or Sleet                       27
Flooding of Slipways/Rivulets       22
Strong Wind                          8
Name: count, dtype: int64

============================================================
Road_Condition
============================================================
Road_Condition
Not Applicable                  33222
No influence on accident        15402
Construction Work / Material      423
Engineering Defect of Road        362
Pot holed                         354
Drainage Ditch                    198
Name: count, dtype: int64

============================================================
Surface_Condition
============================================================
Surface_Condition
Dry                  41635
Others                4399
Not Applicable        3267
Wet                    223
Ditch or Potholed      183
Muddy                  163
Flooded                 91
Name: count, dtype: int64

============================================================
Road_Type
============================================================
Road_Type
NH                     11239
Others                 10526
City or Town Road      10218
Two way                 4688
State Highway           3509
One way                 1700
Residential Street      1585
Not Applicable          1213
Arterial                1117
Service Road             902
Sub Arterial             871
Village Road             821
Expressway               705
Major District Road      347
Minor District Road      301
Mixed                    124
Feeder Road               63
Forest Road               32
Name: count, dtype: int64

============================================================
Road_Character
============================================================
Road_Character
Straight and flat          20145
Others                     14430
Not Applicable              9031
Curve                       4065
Incline                      636
Hump                         545
Slight Curve                 435
Curve and Incline            287
Sharp Curve                  156
Steep Incline or Climb        97
Dip or trough                 63
Crest of hill                 38
Gentle Incline or Climb       32
Name: count, dtype: int64

============================================================
Collision_Type
============================================================
Collision_Type
Vehicle to Vehicle            16425
Hit pedestrian                 9064
Others                         6632
Not Applicable                 5858
Hit and Run                    3780
Rear end                       2495
Head on                        2280
Hit bicyclist                   962
Skidding or Self accident       428
Side swipe                      371
Overturning                     337
Hit fixed object                259
Right Turn Collision            251
Side impact or Right angle      245
Hit parked vehicle              166
Hit animal                      111
Drowned                          99
Hit puchcart                     83
Run Off Road                     65
Hit pedal cyclist                49
Brown                             1
Name: count, dtype: int64

============================================================
Main_Cause
============================================================
Main_Cause
Human Error                42585
Not Applicable              5966
Vehicle Defect              1332
Road Environment Defect       78
Name: count, dtype: int64

============================================================
Severity
============================================================
Severity
Grievous Injury    20628
Simple Injury      12589
Fatal               9072
Damage Only         6975
Not Applicable       697
Name: count, dtype: int64

In [15]:
bengaluru_accidents.isnull().sum()

DISTRICTNAME                    0
UNITNAME                        0
Crime_No                        0
Year                            0
RI                              0
Noofvehicle_involved            0
Accident_Classification         1
Accident_Spot                   1
Accident_Location               1
Accident_SubLocation            1
Accident_SpotB              22794
Main_Cause                      1
Hit_Run                         1
Severity                        1
Collision_Type                  1
Junction_Control                1
Road_Character                  2
Road_Type                       1
Surface_Type                    1
Surface_Condition               1
Road_Condition                  1
Weather                         1
Lane_Type                   42574
Road_Markings               46336
Spot_Conditions             44169
Side_Walk                   44292
RoadJunction                49962
Collision_TypeB             22794
Accident_Road                  14
Landmark_first                131
landmark_second             43704
Distance_LandMark_First       121
Distance_LandMark_Second    46460
Accident_Description          129
Latitude                        0
Longitude                       0
dtype: int64

In [16]:
print("Duplicate rows:", bengaluru_accidents.duplicated().sum())

Duplicate rows: 30

In [17]:
print("Traffic Dataset Columns")
print("-" * 50)

for i, col in enumerate(traffic_df.columns, start=1):
    print(f"{i}. {col}")

print("\nShape:", traffic_df.shape)

Traffic Dataset Columns
--------------------------------------------------
1. Date
2. Area Name
3. Road/Intersection Name
4. Traffic Volume
5. Average Speed
6. Travel Time Index
7. Congestion Level
8. Road Capacity Utilization
9. Incident Reports
10. Environmental Impact
11. Public Transport Usage
12. Traffic Signal Compliance
13. Parking Usage
14. Pedestrian and Cyclist Count
15. Weather Conditions
16. Roadwork and Construction Activity

Shape: (8936, 16)